- name: Copy of csr.conf & installUtilities.sh & metallb-config.yml & traefik-values.yml && keycloak-values.yml to the remote servers
  ansible.builtin.template:
    src: "{{ item }}"
    dest: $HOME
    mode: '0755'
  with_items:
    - templates/csr.conf
    - templates/installUtilities.sh
    - templates/metallb-config.yml
    - templates/traefik-values.yml
    - templates/keycloak-values.yml

- name: Execute the installUtilities.sh script
  command: /bin/sh $HOME/installUtilities.sh

- name: Deleting csr.conf & installUtilities.sh & metallb-config.yml & traefik-values.yml && keycloak-values.yml, tls.key, tls.crt, csr.csr to the remote servers
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - $HOME/csr.conf
    - $HOME/installUtilities.sh
    - $HOME/metallb-config.yml
    - $HOME/traefik-values.yml
    - $HOME/keycloak-values.yml
    - $HOME/tls.key
    - $HOME/tls.crt
    - $HOME/csr.csr