authentik:
    secret_key: "6zWen62yrLGtZJbNae148WF7vimQCaM0Xb2McJvwbT0KSEWH9PkosIs4GQQQldfq2AeaopBxUZFmwUYW"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "wylcpVAmRao0bk1m4ZEW9RdG9A2N2dxyxxmCs30UwbjjWL5uXm"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        enabled: true
        hosts:
            - authentik.traefik.lc

worker:
    volumes:
        - name: blueprints-custom
          configMap:
              name: authentik-blueprints
    volumeMounts:
        - name: blueprints-custom
          mountPath: /blueprints/custom
          readOnly: true

postgresql:
    enabled: true
    auth:
        password: "wylcpVAmRao0bk1m4ZEW9RdG9A2N2dxyxxmCs30UwbjjWL5uXm"
    volumePermissions:
        enabled: false
redis:
    enabled: true
